#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
echo "DEBUG environment variable: $DJANGO_DEBUG"

python manage.py migrate
if [ "$DJANGO_DEBUG" = "true" ]; then
  exec python manage.py runserver 0.0.0.0:8000
else
  exec gunicorn core.wsgi:application --bind 0.0.0.0:8000
fi
