version: '3.3'

volumes:
  drm_prod_postgres_data: { }
  drm_prod_postgres_data_backups: { }
  redis_data:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: demo_django
    depends_on:
      - postgres
    volumes:
      - ./api:/app:z
      - /var/www/demo_app:/var/www/demo_app:z
    env_file:
      - .env
    ports:
      - '8000:8000'
    environment:
      - DJANGO_DEBUG=true  # Set the DEBUG environment variable
    command: /start
    networks:
      - tg_bot


  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    depends_on:
      - django
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: demo_production
    volumes:
      - drm_prod_postgres_data:/var/lib/postgresql/data
      - drm_prod_postgres_data_backups:/backups
    env_file:
      - .env
    networks:
      - tg_bot

  redis:
    image: redis
    container_name: demo_redis
    ports:
      - "6381:6381"
    volumes:
      - redis_data:/data
    command: redis-server --port 6381
    networks:
      - tg_bot

  celeryworkerbeat:
    <<: *django
    container_name: demo_celeryworkerbeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    container_name: demo_celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celerybeat

networks:
  tg_bot:
    driver: bridge
