version: '3.3'

volumes:
  icecream_production_postgres_data: { }
  icecream_production_postgres_data_backups: { }
  icecream_redis_data:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: icecream_production_django
    container_name: icecream_production_django
    depends_on:
      - postgres
    volumes:
      - ./api:/app:z
      - ./media:/media:z
      - ./staticfiles:/staticfiles:z
    env_file:
      - ./.env
    ports:
      - '8040:8000'
    environment:
      - DEBUG=true  # Set the DEBUG environment variable
    command: /start
    networks:
      - tg_bot


  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    depends_on:
      - django
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: icecream_production_postgres_image
    container_name: icecream_production_postgres
    volumes:
      - icecream_production_postgres_data:/var/lib/postgresql/data
      - icecream_production_postgres_data_backups:/backups
    env_file:
      - .env
    networks:
      - tg_bot

  redis:
    image: redis
    ports:
      - "6380:6380"
    volumes:
      - icecream_redis_data:/data
    command: redis-server --port 6380 --appendonly yes
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge